management:
  security:
    enabled: false
kafka:
  groupId: order-service
  bootstrap:
    address: localhost:9092
server:
  port: 8082
logging:
  pattern:
    level: "[${spring.application.name:-},%X{traceId},%X{spanId}] %-5p [%t] %C{2} - %m%n"
spring:
  sleuth:
    traceId128: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${db.username}
    password: ${db.password}
    url: jdbc:mysql://localhost:3306/order_service?createDatabaseIfNotExist=true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-id:${random.value}
        serviceName: dk-${spring.application.name}
        healthCheckInterval: 15s