server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: ${db.username}
    password: ${db.password}
    url: jdbc:mysql://localhost:3306/order_service?createDatabaseIfNotExist=true
